// Reranker tokenizer equivalence golden test (snapshot-only form).
//
// STATUS: 4/6 buckets verified against frozen xenova snapshot.
//
// Originally this test compared @xenova/transformers (Node JS) against HF
// `tokenizers` (Rust Python). After the migration, @xenova/transformers is
// no longer installed, so we now compare Python tokenization against a frozen
// xenova snapshot captured at the previous commit
// (tests/fixtures/reranker-tokenizer-snapshot.json, generated by
// scripts/dump_xenova_snapshot.mjs while xenova was still installed).
//
// The corpus + snapshot are effectively FROZEN after this commit. To add a new
// pair, you must `git checkout <pre-this-commit-sha>`, run dump_xenova_snapshot.mjs
// against the extended corpus, and copy the snapshot back. Or accept that the
// new pair has no xenova baseline (Python-only).
//
// Two buckets remain accepted-mismatch (`4_emoji_zwj` and
// `2_ascii_long_truncating`): xenova has UTF-16 surrogate-pair splitting and
// truncation-vs-template-budget bugs that the xenova-compat patching in
// reranker_server.py / dump_tokens.py does not emulate. See Task 4.5 commit
// message for the full breakdown.
//
// Gated by WIGOLO_RERANKER_TEST=1.

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { spawn } from 'node:child_process';

const corpus = JSON.parse(
  readFileSync(join(__dirname, '..', 'fixtures', 'reranker-tokenizer-corpus.json'), 'utf-8'),
) as { buckets: Record<string, { query: string; doc: string }[]> };

const snapshot = JSON.parse(
  readFileSync(join(__dirname, '..', 'fixtures', 'reranker-tokenizer-snapshot.json'), 'utf-8'),
) as {
  maxLength: number;
  models: Record<
    string,
    Record<string, { input_ids: number[]; attention_mask: number[]; token_type_ids: number[] }[]>
  >;
};

const DATA_DIR = process.env.WIGOLO_DATA_DIR ?? join(homedir(), '.wigolo');
const DUMP_SCRIPT = join(__dirname, '..', 'fixtures', 'dump_tokens.py');
const VENV_PYTHON = join(DATA_DIR, 'searxng', 'venv', 'bin', 'python');
const PYTHON = existsSync(VENV_PYTHON) ? VENV_PYTHON : 'python3';

const MODELS = ['bge-reranker-v2-m3', 'ms-marco-MiniLM-L-12-v2'] as const;
const MAX_LENGTH = snapshot.maxLength;

interface TokenDump {
  input_ids: number[];
  attention_mask: number[];
  token_type_ids: number[];
  error?: string;
}

async function dumpPython(modelId: string, query: string, doc: string): Promise<TokenDump> {
  return new Promise((resolve, reject) => {
    const modelDir = join(DATA_DIR, 'models', modelId);
    const proc = spawn(PYTHON, [DUMP_SCRIPT, modelDir, String(MAX_LENGTH)], {
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    proc.stdout.on('data', (d) => (stdout += d.toString()));
    proc.stderr.on('data', (d) => (stderr += d.toString()));
    proc.on('close', (code) => {
      if (code !== 0) return reject(new Error(`dump_tokens exit ${code}: ${stderr}`));
      try {
        resolve(JSON.parse(stdout));
      } catch {
        reject(new Error(`dump_tokens output not JSON: ${stdout}`));
      }
    });
    proc.stdin.write(JSON.stringify({ query, doc }));
    proc.stdin.end();
  });
}

const skip = !process.env.WIGOLO_RERANKER_TEST;

// PRESERVED from Task 4.5: buckets where xenova bugs make patching unrecoverable.
const EXPECTED_MISMATCH_BUCKETS = new Set(['4_emoji_zwj', '2_ascii_long_truncating']);

const warnedMissingModels = new Set<string>();

describe.skipIf(skip)('reranker tokenizer equivalence (Python tokenizers vs frozen xenova snapshot)', () => {
  for (const modelId of MODELS) {
    const modelDir = join(DATA_DIR, 'models', modelId);
    const modelMissing = !existsSync(modelDir);
    const snapshotMissing = !snapshot.models[modelId];
    if ((modelMissing || snapshotMissing) && !warnedMissingModels.has(modelId)) {
      warnedMissingModels.add(modelId);
      const reason = modelMissing ? `model dir ${modelDir}` : 'no snapshot entry';
      process.stderr.write(
        `[reranker-tokenizer-equivalence] model "${modelId}" not available (${reason}); skipping.\n`,
      );
    }
    for (const [bucket, pairs] of Object.entries(corpus.buckets)) {
      const bucketSkipped = EXPECTED_MISMATCH_BUCKETS.has(bucket) || modelMissing || snapshotMissing;
      (bucketSkipped ? describe.skip : describe)(`${modelId} :: ${bucket}`, () => {
        for (let i = 0; i < pairs.length; i++) {
          const { query, doc } = pairs[i];
          const expected = snapshot.models[modelId]?.[bucket]?.[i];
          it(`pair ${i + 1}`, async () => {
            expect(expected, `snapshot entry missing for ${modelId}/${bucket}/pair ${i + 1}`).toBeDefined();
            const py = await dumpPython(modelId, query, doc);
            expect(py.error).toBeUndefined();
            expect(py.input_ids).toEqual(expected.input_ids);
            expect(py.attention_mask).toEqual(expected.attention_mask);
            expect(py.token_type_ids).toEqual(expected.token_type_ids);
          });
        }
      });
    }
  }
});
